INSERT INTO phrase (word, id_per, level) VALUES ('ja', 0, 10)
INSERT INTO phrase (word, id_per, level) VALUES ('moj', 0, 10)
INSERT INTO phrase (word, id_per, level) VALUES ('on', 1, 10)
INSERT INTO phrase (word, id_per, level) VALUES ('oni', 1, 10)
INSERT INTO phrase (word, id_per, level) VALUES ('moim', 0, 10)
INSERT INTO phrase (word, id_per, level) VALUES ('my', 0, 10)
INSERT INTO phrase (word, id_per, level) VALUES ('nasz', 0, 10)
INSERT INTO phrase (word, id_per, level) VALUES ('potrzebujê', 0, 10)
INSERT INTO phrase (word, id_per, level) VALUES ('chcê', 0, 10)
INSERT INTO phrase (word, id_per, level) VALUES ('chcia³bym', 0, 10)
INSERT INTO phrase (word, id_per, level) VALUES ('zgadzam', 0, 10)
INSERT INTO phrase (word, id_per, level) VALUES ('decyzja', 0, 10)
INSERT INTO phrase (word, id_per, level) VALUES ('wybór', 0, 10)
INSERT INTO phrase (word, id_per, level) VALUES ('g³osowanie', 0, 10)
INSERT INTO phrase (word, id_per, level) VALUES ('wybory', 0, 10)

